### ISSUE TITLE
alexellis2/visualizer-arm tag 0.4 missing on Docker Hub

### ISSUE THREAD

**Issue by RandomByte** [dockersamples/docker-swarm-visualizer#101]
Tag 0.4 is missing in the [alexellis2/visualizer-arm](https://hub.docker.com/r/alexellis2/visualizer-arm/tags/) repository on Docker Hub.

Even though not available, 0.4 is [referenced in the readme](https://github.com/dockersamples/docker-swarm-visualizer#running-on-arm):  
> $ docker service create \\
>   --name=viz \\
>   --publish=8080:8080/tcp \\
>   --constraint=node.role==manager \\
>   --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \\
>   **alexellis2/visualizer-arm:0.4**

**Comment by ManoMarks** [comment]
@alexellis

**Comment by ehubbard** [comment]
Does anyone have a clone of this they could put up DockerHub?

**Comment by alexellis** [comment]
I checked and the readme says to use the `latest` tag. `0.4` is mentioned in another place so I can update that to `latest` as that would be clearer. 

To check for latest Docker Hub images go here:

https://hub.docker.com/r/alexellis2/visualizer-arm/tags/

@RandomByte @ehubbard 

Full instructions are given for how you can build this yourselves.. I'm not sure where the confusion is.. this is the part of the readme with the instructions:

<img width="1105" alt="screen shot 2018-02-10 at 19 03 11" src="https://user-images.githubusercontent.com/6358735/36065635-660f36da-0e95-11e8-8761-f6fbd5d1d05a.png">

At any time you can clone the git repo and build your own image.

**Comment by RandomByte** [comment]
My only concern was the `docker service create` example, which mentioned the non-existing 0.4 tag and therefore failed to execute.

#104 looks good and resolves this issue 👍
