### ISSUE TITLE
Vsualizer for Arm

### ISSUE THREAD

**Issue by coop59** [dockersamples/docker-swarm-visualizer#112]
Hello,

I ran this on my docker swarm via this command: **sudo docker service create --name cfviz --publish 8080:8080/tcp --constraint node.role==manager --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock alexellis2/visualizer-arm:latest**

My Problem is it is showing the visulizer only. I have both the visualizer and portainer running on the Leader/Manager of the swarm. Visualizer shows manager and 3 worker nodes but the manager only shows one container running when there are two running.

<img width="967" alt="screen shot 2018-07-16 at 8 34 37 am" src="https://user-images.githubusercontent.com/26882630/42758908-221d3036-88d3-11e8-8787-f00e116862fb.png">

pi@cfDOC1:~ $ docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                    NAMES
083892995cf1        alexellis2/visualizer-arm:latest   "/usr/bin/entry.sh n…"   13 hours ago        Up 13 hours         8080/tcp                 cfviz.1.x7wqlrqiy1nuhae4tguvbx68e
41700e18f455        hypriot/rpi-portainer              "/portainer"             15 hours ago        Up 6 hours          0.0.0.0:9000->9000/tcp   nifty_poitras

**Comment by ManoMarks** [comment]
obsoleted by #105
