### ISSUE TITLE
Docker service creation taking more time

### ISSUE THREAD

**Issue by hariharan1993** [dockersamples/docker-swarm-visualizer#113]
i'm new to this docker service creation please help me if i'm wrong , i executed this command 
**docker service create --name "testApp" -p 8000:8000 testApp** , its taking too long time to execute so that my shell is getting timeout .
anything wrong am i doing here??

**Comment by BretFisher** [comment]
1. you need a space between port and image name `-p 8000:8000 testApp`
2. I recommend reading up on [services in the docs](https://docs.docker.com/engine/swarm/how-swarm-mode-works/services/) and then also look at the [syntax for the command](https://docs.docker.com/engine/reference/commandline/service_create/).
