### ISSUE TITLE
blue screen but showing nothing

### ISSUE THREAD

**Issue by MerouaneBen** [dockersamples/docker-swarm-visualizer#117]
hi,
I'm running into this issue for hours and don't see the reason behind this error: 
everytime I run the visualizer  i get this screen : 
![image](https://user-images.githubusercontent.com/12593367/44315152-539b5480-a3ef-11e8-9789-9a2463ae41a3.png)

I'm using digital ocean VMs, and this the command i used  to start the visualizer (i've use it with the variable -e HOST and without it, but same result) : 
```
docker run --rm -it -d -p 5000:8080 -e HOST=178.128.237.43 -v /var/run/docker.sock:/var/run/docker.sock dockersamples/visualizer 
```
This is the version of docker on the my swarm cluster

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   f150324782
 Built:        Wed May 16 22:27:45 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.06.0-ce
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   0ffa825
  Built:        Wed Jul 18 19:10:42 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
any help with that please!
many thanks

**Comment by BretFisher** [comment]
Are you in swarm mode? Describe your server setup

**Comment by MerouaneBen** [comment]
thanks for the reply @BretFisher,
yeah I've enabled swarm mode, i'm using one worker and one manager right now for testing purposes (I've also tried with 2 workers and same result). I'm using centos 7.5 x64 images for my VMs (I've also  tried with ubuntu 16.04x64, and same results) ..
 
![swarm](https://user-images.githubusercontent.com/12593367/44316910-4fc1ff00-a3fc-11e8-90a5-01655f3b6b20.png)
 here it is the output of the command `docker info`: 
```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 18.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:1-88080694-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 331MB
 Data Space Total: 107.4GB
 Data Space Available: 62.28GB
 Metadata Space Used: 1.032MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: n09r9ssur9ldf8ea27nivappe
 Is Manager: true
 ClusterID: gxacgxhx7ebt9swa2eq68itlp
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 178.128.237.43
 Manager Addresses:
  178.128.237.43:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.2.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.701GiB
Name: manager1
ID: 66KP:5UCU:SS74:4MMN:TMSG:D7U7:V36W:D2XB:OPDO:B5L5:7XG7:XIOF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: merouaneb
Registry: https://index.docker.io/v1/
Labels:
 provider=digitalocean
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-ip6tables is disabled

```

**Comment by malisevs** [comment]
Encountered the same problem. Using Amazon Linux AMI. 

` Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.4
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Fri Jul 20 19:24:06 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm
`
`
Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6/18.03.1-ce
  Built:        Fri Jul 20 19:25:23 2018
  OS/Arch:      linux/amd64
  Experimental: false
`

From browsers console:
`data-provider.js:149 Uncaught (in promise) TypeError: h.default.findWhere is not a function
    at m (data-provider.js:149)
    at Array.forEach (<anonymous>)
    at w (data-provider.js:222)
    at data-provider.js:283`

**Comment by MerouaneBen** [comment]
I even tired with a local virtualbox cluster, and same issue. could the issue be related to the version of docker running  ?: 
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   f150324782
 Built:        Wed May 16 22:27:45 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.06.0-ce
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   0ffa825
  Built:        Wed Jul 18 19:13:39 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by malisevs** [comment]
Just checked: 
/apis/nodes returns nodes
/apis/services returns services
/apis/tasks returns tasks

**Comment by malisevs** [comment]
https://github.com/dockersamples/docker-swarm-visualizer/pull/116/files this is the cause of this bug. Just checked and it works, if you use 3.10.1 version.

**Comment by MerouaneBen** [comment]
thanks @malisevs  your fix works.

**Comment by ManoMarks** [comment]
Fixed for now, ultimately we need to remove the dependency to lodash
