### ISSUE TITLE
Show engine labels on nodes.

### ISSUE THREAD

**Issue by eliasbrange** [dockersamples/docker-swarm-visualizer#122]
The visualizer only shows `node` labels and not `engine` labels. We are using engine labels for non-security related placement constraints so that the nodes can handle the labeling in a decentralized manner. Would it be possible to show these in the visualizer alongside the node labels?

**Comment by BretFisher** [comment]
That isn't possible in this sample apps current design, but check out https://www.portainer.io which can have agents on each node.
