### ISSUE TITLE
docker pull manomarks/visualizer Using default tag: latest Error response from daemon: manifest for manomarks/visualizer:latest not found

### ISSUE THREAD

**Issue by zkl99999** [dockersamples/docker-swarm-visualizer#123]
docker pull manomarks/visualizer
Using default tag: latest
Error response from daemon: manifest for manomarks/visualizer:latest not found

my docker version  
docker --version
Docker version 18.09.0, build 4d60db4
ubuntu16.04 64bits

**Comment by ManoMarks** [comment]
use dockersamples/visualizer
