### ISSUE TITLE
Scaling visualizer

### ISSUE THREAD

**Issue by 7hill** [dockersamples/docker-swarm-visualizer#132]
Hi,

The visualizer service can be started using the below command in the docker swarm manager,
but if the manager node is down the visualizer not accessible. The visualizer also getting down not scaled into other running nodes.

**docker service create -p 8080:8080 --constraint=node.role==manager \
 --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
 --name visualizer dockersamples/visualizer**

So the visualizer availability not ensured if the manager node on swarm went down. I think this issue occurs because of constraint added in above command(**--constraint=node.role==manager**)

Is there any option to run the visualizer(automatically) on the worker node if the manager node went offline?

Is it possible to add worker role also in --constraint? please provide command.

**Comment by 7hill** [comment]
Is there any possibility to run the visualizer on TLS/HTTPS?

**Comment by BretFisher** [comment]
1. The visualizer requires access to the docker engine on a manager node, so running on worker nodes in its current design isn't possible.
2. To add a certificate to container apps, you usually run a front-end proxy like Nginx or Traefik to provide TLS for backend web-server containers.
