### ISSUE TITLE
Showing red but no details are there, how to trace that?

### ISSUE THREAD

**Issue by ukreddy-erwin** [dockersamples/docker-swarm-visualizer#143]
I have running 4 docker swarm services on three different nodes. One is manager among them.

![image](https://user-images.githubusercontent.com/21240709/122180471-152b8a00-cea6-11eb-959e-856660117ca4.png)

Why is the oracle container (running in manager) is showing red even the status is running.
Where to check what is the issue?

**Comment by BretFisher** [comment]
The replica status color is the dot. The box color is random, and used match replicas of the same service.

**Comment by ukreddy-erwin** [comment]
Only few are showing in red.
[Image]



Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
