### ISSUE TITLE
Node is continuosly removed

### ISSUE THREAD

**Issue by ukreddy-erwin** [dockersamples/docker-swarm-visualizer#144]
I have added 2 swam workers and a worker node is continuously removed from swarm.

![image](https://user-images.githubusercontent.com/21240709/125561330-9c37eed8-9eda-42b1-a204-64bae456f1d1.png)

After sometime, it will gain back.
But the machine is running correctly without any issue when I connect with ssh.

These are aws machines with all ports and access enabled

How to troubleshoot this?

**Comment by BretFisher** [comment]
Sorry, this sample app repo isn't for troubleshooting Swarm. Closing.
