### ISSUE TITLE
No such container Message

### ISSUE THREAD

**Issue by alexrun** [dockersamples/docker-swarm-visualizer#61]
When you click on a container inside a different note than the visualizer container as seen in the next image

![image](https://cloud.githubusercontent.com/assets/2502143/23612879/8a100950-0253-11e7-8a0d-bb6c1e6888d9.png)

You get the following json response

![image](https://cloud.githubusercontent.com/assets/2502143/23612924/b051a9d4-0253-11e7-99a3-e6e7337240c9.png)

I spec to get the same kind of response that when the container is in the same node as the visualizer container.

![image](https://cloud.githubusercontent.com/assets/2502143/23613237/f8ce2132-0254-11e7-952c-112ac986f992.png)

**Comment by ManoMarks** [comment]
Fixed in #83

**Comment by alexrun** [comment]
Well, that wasn't what I had in mind. You removed the onClick function on each container. What I was suggesting to do was to allow the user to view the info of any containers in any node.

**Comment by ManoMarks** [comment]
It wasn't working reliably even on the node that the visualizer is on. Also that information isn't being used in the visualization.
