### ISSUE TITLE
Understand service constraints

### ISSUE THREAD

**Issue by robbiewxyz** [dockersamples/docker-swarm-visualizer#62]
I've using a global service with label constraints to run my database containers only on specific nodes.  So I created the service like this:

```
docker service create --name rethinkdb-master --mode global --constraint node.labels.rethink-role==master rethinkdb
```

![visualizer screenshot](https://cloud.githubusercontent.com/assets/7308014/24163890/79f92bde-0e31-11e7-9a2e-6640a9dc9b27.png)

The `rethink-master` processes on the second two nodes will never start because of their constraints.

Can we somehow detect that they're not eligible to run and have them hidden completely instead of giving the appearance that they've crashed on startup?

**Comment by ManoMarks** [comment]
No, I think you would want to show that they aren't working.
