### ISSUE TITLE
[FEATURE REQUEST] displaying stdout hover

### ISSUE THREAD

**Issue by wannaknowmo** [dockersamples/docker-swarm-visualizer#71]
hi,
would like to know if it would be feasible to display the stdout of a container with a onmouseover?

**Comment by pahakalle** [comment]
Should be possible with dockerodes [Helper functions](https://www.npmjs.com/package/dockerode#helper-functions)

**Comment by BretFisher** [comment]
Will likely never happen so I'll mark as won't fix :(
