### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by duffbuster** [dockersamples/docker-swarm-visualizer#72]
<img width="490" alt="screen shot 2017-06-02 at 4 41 15 pm" src="https://cloud.githubusercontent.com/assets/1220827/26744059/5486a858-47b2-11e7-9ce3-e73de68da8cb.png">

Seeing a css issue on hover of the node elements. Looks like the `position: absolute` on the div is causing the problem.

**Comment by ManoMarks** [comment]
Fixed in #73
