### ISSUE TITLE
[FEATURE REQUEST] Display 'drained' nodes

### ISSUE THREAD

**Issue by SplinterHead** [dockersamples/docker-swarm-visualizer#75]
We have our mangers configured to 'drained' so they don't run containers automatically. It would be good if we could grey them out or somehow show that they are drained. 
`docker node update --availability drain <NODE>`

The setting is readable in the `docker node inspect` command json, so would be good to expose that.

Thanks, 
PS. Loving this project so far

**Comment by BretFisher** [comment]
Similar to #58 so I'll close this one in favor of that one.
