### ISSUE TITLE
sorry  I can not understand what these colors represent for?

### ISSUE THREAD

**Issue by zhoulouzi** [dockersamples/docker-swarm-visualizer#80]
what does the border in different colors means ？ about  the container resources situation ？

**Comment by zhoulouzi** [comment]
maybe a more detail README.md thanks.

**Comment by stewshka** [comment]
Looking at the code, seems that it is a randomly generated color based on the service ID.

**Comment by AshleyAitken** [comment]
Perhaps the colour could relate to health of the container?  Or containers from the same stack could have the same colour?

**Comment by asloan7** [comment]
The random border colours help the eye differentiate containers from each other. Container health would hopefully be all green for all containers! The dot before the container name already shows green/red (ie. during startup). 

Maybe better than random, the colour could be derived from a hash of the name or ID, so the colours are different but stay the same after visualizer restarts.

**Comment by ManoMarks** [comment]
This is a sample app, not meant for production. If anyone wants to submit a PR we would review.
