### ISSUE TITLE
Code style updates

### ISSUE THREAD

**Issue by stevelacy** [dockersamples/docker-swarm-visualizer#85]
Would you accept a PR to unify all the code style?
For instance, this has some crazy indentation: https://github.com/dockersamples/docker-swarm-visualizer/blob/master/server.js#L84
I'd be following this file's style: https://github.com/dockersamples/docker-swarm-visualizer/blob/master/karma.conf.js

Cheers

**Comment by ManoMarks** [comment]
Reviewing old issues. Feel free to submit a PR and we'll review
