### ISSUE TITLE
Make it possible use socket-proxy

### ISSUE THREAD

**Issue by holgerstolzenberg** [dockersamples/docker-swarm-visualizer#96]
In my setup, I like to use "rancher/socat" which exposes the Docker socket to the my swarm via TCP.
I then connect apps (e.g. Traefik.io) that need the socket to that TCP endpoint. This means I only have to mount the managers Docker socket as volume once.

Please provide an option to connect the visualizer to a TCP exposed [possibly non-secured] socket.

**Comment by ManoMarks** [comment]
We don't want to make this sample application too complicated.
